datasets:
  qvh: # name of the dataset builder
    # data_dir: ${env.data_dir}/datasets
    data_type: videos # [images|videos|features]
    build_info:
      # Be careful not to append minus sign (-) before split to avoid itemizing
      annotations:
        train:
          url: Datasets/QVH/train.json
          storage: Datasets/QVH/train.json
        val:
          url: Datasets/QVH/val.json
          storage: Datasets/QVH/val.json
        test:
          url: Datasets/QVH/test.json
          storage: Datasets/QVH/test.json
      videos:
        storage: Datasets/QVH/videos