datasets:
  star: # name of the dataset builder
    # data_dir: ${env.data_dir}/datasets
    data_type: videos # [images|videos|features]
    build_info:
      # Be careful not to append minus sign (-) before split to avoid itemizing
      annotations:
        train:
          url: Datasets/STAR/train.json
          storage: Datasets/STAR/train.json
        val:
          url: Datasets/STAR/val.json
          storage: Datasets/STAR/val.json
        test:
          url: Datasets/STAR/val.json
          storage: Datasets/STAR/val.json
      videos:
        storage: Datasets/STAR/Charades_v1_480